### ISSUE TITLE
Error with sample script

### ISSUE THREAD

**Issue by AgoraSecurity** [Strvm/musicxmatch-api#3]
When using:
```python
import json
from musicxmatch_api import MusixMatchAPI
api = MusixMatchAPI()
search = api.search_tracks("skyfall")
print(json.dumps(search, indent=4))
```

I get:
```bash
(.venv) ➜  test git:(main) ✗ python get_lyric.py
Traceback (most recent call last):
  File "/home/m/src/test/get_lyric.py", line 3, in <module>
    api = MusixMatchAPI()
  File "/home/m/src/.venv/lib/python3.10/site-packages/musicxmatch_api/main.py", line 37, in __init__
    self.secret = self.get_secret()
  File "/home/m/src/.venv/lib/python3.10/site-packages/musicxmatch_api/main.py", line 50, in get_secret
    SIGNATURE_KEY_BASE_URL + self.get_latest_app(),
  File "/home/m/src/.venv/lib/python3.10/site-packages/musicxmatch_api/main.py", line 44, in get_latest_app
    last_script_src = script_tags[-1]["src"]
IndexError: list index out of range
(.venv) ➜  test git:(main) ✗ python get_lyric.py
```

**Comment by fann22** [comment]
facing the same

**Comment by Strvm** [comment]
Hi both (@AgoraSecurity , @fann22 ), I pushed a temporary fix and should work now (please update to latest version)
